version: "3"
services:
  mysql:
    image: "mymysql:5.7.22"
#    restart: always
    volumes:
      - "/data/docker/mysql/log:/var/log/mysql"
      - "/usr/local/var/mysql:/var/lib/mysql"
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Hong_Kong
      - LANG=en_US.UTF-8
    extra_hosts:
      - "hypervisor:192.168.1.180"
    networks:
      webnet:
        aliases:
          - "my-docker-mysql"
  redis:
    image: "myredis:4.0.9"
#    restart: always
    volumes:
      - "/data/docker/redis/data:/data"
    ports:
      - "16379:6379"
    environment:
      - TZ=Asia/Hong_Kong
      - LANG=en_US.UTF-8
    sysctls:
      - net.core.somaxconn=65535
    extra_hosts:
      - "hypervisor:192.168.1.180"
    networks:
      webnet:
        aliases:
          - "my-docker-redis"
    command: ["redis-server", "--appendonly", "yes" ]
  php:
    image: "myphp-fpm:7.2.4"
#    restart: always
    volumes:
      - "/data/www:/data/www"
      - "/data/docker/php72:/data/php"
    ports:
      - "19000:9000"
    depends_on:
      - mysql
      - redis
    environment:
      - TZ=Asia/Hong_Kong
      - LANG=en_US.UTF-8
    extra_hosts:
      - "hypervisor:192.168.1.180"
    networks:
      webnet:
        aliases:
          - "my-docker-php-fpm"
  nginx:
    image: "mynginx:1.12.2"
#    restart: always
    volumes:
      - "/data/docker/nginx/log:/var/log/nginx"
      - "/data/docker/nginx/conf/conf.d:/etc/nginx/conf.d"
      - "/data/docker/nginx/conf/extra:/etc/nginx/extra"
      - "/data/docker/nginx/ssl:/etc/nginx/ssl"
      - "/data/www:/data/www"
    ports:
      - "180:80"
    depends_on:
      - php
    environment:
      - DOLLAR=$$
      - FASTCGI_HOST=my-docker-php-fpm
      - FASTCGI_PORT=9000
      - TZ=Asia/Hong_Kong
      - LANG=en_US.UTF-8
    extra_hosts:
      - "hypervisor:192.168.1.180"
    networks:
      webnet:
        aliases:
          - "my-docker-nginx"
    command: /bin/bash -c "envsubst < /etc/nginx/extra/php-fpm.template > /etc/nginx/customized/php-fpm.conf && nginx -g 'daemon off;'"

#  'mongo-express':
#    image: "hardyliu/mymongo-express"
#    restart: "always"
#    ports:
#      - "8081:8081"
#    depends_on:
#      - mongodb
#    environment:
#      - TZ=Asia/Hong_Kong
#      - LANG=en_US.UTF-8
#      - ME_CONFIG_MONGODB_SERVER=my-docker-mongodb
#      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongopassword
#    networks:
#      webnet:
#        ipv4_address: 172.28.1.101
#        aliases:
#          - "my-docker-mongo-express"
#  parity:
#    image: "parity/parity:stable"
#    restart: "no"
#    volumes:
#      - "/data/docker/parity:/data/docker/parity"
#    ports:
#      - "8545:8545"
#      - "8546:8546"
#    command:
##      - "--config"
##      - "/data/docker/parity/etc/config.toml"
##      - "--chain=/data/docker/parity/etc/dev-chain.json"
#      - "--chain=dev"
#      - "--gas-floor-target=20000000"
#      - "--base-path=/data/docker/parity/data"
#      - "--jsonrpc-interface=all"
#      - "--jsonrpc-apis=all"
#      - "--jsonrpc-hosts=all"
#      - "--jsonrpc-cors=all"
#      - "--ws-interface=all"
#      - "--ws-apis=all"
#      - "--ws-hosts=all"
#      - "--ws-origins=all"
#      - "--tracing=on"
#      - "--fat-db=on"
#      - "--pruning=archive"
#    networks:
#      webnet:
#        ipv4_address: 172.28.1.1
#        aliases:
#          - "my-docker-parity"

#  'etherchain-light':
#    image: "hardyliu/mynode:8.11.3"
#    restart: "no"
#    volumes:
#      - "/data/www/ethereum_project/etherchain-light:/data/www/ethereum_project/etherchain-light"
#    ports:
#      - 3000:3000
#    depends_on:
#      - parity 
#    environment:
#      - TZ=Asia/Hong_Kong
#      - LANG=en_US.UTF-8
networks:
  webnet:
