version: "3"
services:
  mysql:
    image: "mymysql:5.7.22"
#    restart: always
    volumes:
      - "/data/docker/mysql/log:/var/log/mysql"
      - "/usr/local/var/mysql:/var/lib/mysql"
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    extra_hosts:
      - "hypervisor:192.168.1.180"
    networks:
      webnet:
        aliases:
          - "my-docker-mysql"
  redis:
    image: "myredis:4.0.9"
#    restart: always
    volumes:
      - "/data/docker/redis/data:/data"
    ports:
      - "16379:6379"
    extra_hosts:
      - "hypervisor:192.168.1.180"
    networks:
      webnet:
        aliases:
          - "my-docker-redis"
    command: ["redis-server", "--appendonly", "yes" ]
  php:
    image: "myphp-fpm:7.2.4"
#    restart: always
    volumes:
      - "/data/www:/data/www"
      - "/data/docker/php72:/data/php"
    ports:
      - "19000:9000"
    depends_on:
      - mysql
      - redis
    extra_hosts:
      - "hypervisor:192.168.1.180"
    networks:
      webnet:
        aliases:
          - "my-docker-php-fpm"
  nginx:
    image: "mynginx:1.12.2"
#    restart: always
    volumes:
      - "/data/docker/nginx/log:/var/log/nginx"
      - "/data/docker/nginx/conf/conf.d:/etc/nginx/conf.d"
      - "/data/docker/nginx/conf/extra:/etc/nginx/extra"
      - "/data/docker/nginx/ssl:/etc/nginx/ssl"
      - "/data/www:/data/www"
    ports:
      - "180:80"
    depends_on:
      - php
    environment:
      - DOLLAR=$$
      - FASTCGI_HOST=my-docker-php-fpm
      - FASTCGI_PORT=9000
    extra_hosts:
      - "hypervisor:192.168.1.180"
    networks:
      webnet:
        aliases:
          - "my-docker-nginx"
    command: /bin/bash -c "envsubst < /etc/nginx/extra/php-fpm.template > /etc/nginx/customized/php-fpm.conf && nginx -g 'daemon off;'"
networks:
  webnet:
