version: "3"
services:
  rabbitmq:
    image: "myrabbitmq"
    restart: always
    volumes:
      - "/data/docker/rabbitmq/log:/var/log/rabbitmq"
      - "/data/docker/rabbitmq/data:/var/lib/rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    environment:
      - HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    extra_hosts:
      - "hypervisor:192.168.1.180"
    networks:
      rabbitmqnet:
        aliases:
          - "my-rabbitmq"
networks:
  rabbitmqnet:
